Aaaand Joyent provisions/deploys work! (need some features & some testing but damn it they work)

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -40,6 +40,9 @@ EOF
 #
 
 deploy() {
+  config_section $ENV || abort "[$ENV] config section not found in deploy.conf"
+  test -z "$ENV" && usage && exit
+
   INSTANCE=`config_get instance`
   case $INSTANCE in
     linode) invoke "./linode/deploy"; ;;
@@ -47,5 +50,21 @@ deploy() {
     *) abort "instance type must be specified in deploy.conf"; ;;
   esac
 }
+
+while test $# -ne 0; do
+  arg=$1; shift
+  case $arg in
+    -h|--help) usage; exit ;;
+    -V|--version) version; exit ;;
+    config) config $@; exit ;;
+    *)
+      if test -z "$ENV"; then
+        ENV=$arg;
+      else
+        REF="$REF $arg";
+      fi
+      ;;
+  esac
+done
 
 deploy
diff --git a/scripts/provision b/scripts/provision
--- a/scripts/provision
+++ b/scripts/provision
@@ -42,12 +42,33 @@ EOF
 #
 
 provision() {
+  config_section $ENV || abort "[$ENV] config section not found in deploy.conf"
+  test -z "$ENV" && usage && exit
+
   INSTANCE=`config_get instance`
+  echo "INSTANCE: $INSTANCE"
   case $INSTANCE in
     linode) invoke "./linode/provision"; ;;
     joyent) invoke "./joyent/provision"; ;;
     *) abort "instance type must be specified in deploy.conf"; ;;
   esac
 }
+
+while test $# -ne 0; do
+  arg=$1; shift
+  case $arg in
+    -h|--help) usage; exit ;;
+    -V|--version) version; exit ;;
+    config) config $@; exit ;;
+    *)
+      if test -z "$ENV"; then
+        ENV=$arg;
+      else
+        REF="$REF $arg";
+      fi
+      ;;
+  esac
+done
+
 
 provision
